package zadanie.decerto.numbers.exception;

public class DataProviderException extends RuntimeException {

    public DataProviderException(Throwable cause) {
        super(cause);
    }

    public DataProviderException(String cause) {
        super(cause);
    }

}
